-- Migration: Create facility_hours table with proper schema
-- This ensures the facility_hours table has the correct structure

-- Create facility_hours table if it doesn't exist
CREATE TABLE IF NOT EXISTS facility_hours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  facility_id BIGINT NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
  day TEXT NOT NULL,
  open BOOLEAN NOT NULL DEFAULT false,
  start_time TIME NOT NULL DEFAULT '09:00:00',
  end_time TIME NOT NULL DEFAULT '17:00:00',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Ensure each facility has only one entry per day
  UNIQUE(facility_id, day)
);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_facility_hours_facility_id ON facility_hours(facility_id);
CREATE INDEX IF NOT EXISTS idx_facility_hours_day ON facility_hours(day);
CREATE INDEX IF NOT EXISTS idx_facility_hours_open ON facility_hours(open);

-- Add comments to document the fields
COMMENT ON TABLE facility_hours IS 'Operating hours for each facility by day';
COMMENT ON COLUMN facility_hours.facility_id IS 'Reference to the facility';
COMMENT ON COLUMN facility_hours.day IS 'Day of the week (Monday, Tuesday, etc.)';
COMMENT ON COLUMN facility_hours.open IS 'Whether the facility is open on this day';
COMMENT ON COLUMN facility_hours.start_time IS 'Opening time for this day';
COMMENT ON COLUMN facility_hours.end_time IS 'Closing time for this day';

-- Create trigger to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_facility_hours_updated_at ON facility_hours;
CREATE TRIGGER update_facility_hours_updated_at 
    BEFORE UPDATE ON facility_hours 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();
